from ex1_humano.humano import Pessoa
from ex2_gato_cachorro.cachorro import Cachorro
from ex2_gato_cachorro.gato import Gato
from ex3_carro.carro import Carro
from ex4_banco.banco import Banco
from ex4_banco.titular import Titular
from ex5_escolar.estudante import Estudante
from ex5_escolar.curso import Curso
from ex6_biblioteca.bibliotecario import Bibliotecario
from ex6_biblioteca.livro import Livro
from ex7_dep_func.departamento import Departamento
from ex7_dep_func.funcionario import Funcionario
from ex8_ecommerce.clientes import Cliente
from ex8_ecommerce.produtos import Produto
from ex9_filmes.categorias import Categoria
from ex9_filmes.filmes import Filme
from ex10_pedidos.clientes import Cliente
from ex10_pedidos.pedidos import Pedidos